name: user_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/chef.png  # Ensure this path is correct
    - lib/assets/google_icon.png
    - lib/assets/facebook_icon.png
    - lib/assets/home_logo.png
    - lib/assets/dish_image.png
    - lib/assets/profile_image.png
    - lib/assets/done_right.png
