// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1F9hCjHBRhqkoukjnK1qnvZTcktjRzGI',
    appId: '1:831849410502:android:3f8227b03cb27334da0cc7',
    messagingSenderId: '831849410502',
    projectId: 'app-project-6d5d5',
    storageBucket: 'app-project-6d5d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPTr5AYiY2PTqgLy-uvJ0r1XFQE-q8t4g',
    appId: '1:831849410502:ios:0abd7623fa2e2bddda0cc7',
    messagingSenderId: '831849410502',
    projectId: 'app-project-6d5d5',
    storageBucket: 'app-project-6d5d5.appspot.com',
    iosClientId: '831849410502-n5esuue3tmed7ovfmefavg4mrbcbfjd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.userApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPTr5AYiY2PTqgLy-uvJ0r1XFQE-q8t4g',
    appId: '1:831849410502:ios:0abd7623fa2e2bddda0cc7',
    messagingSenderId: '831849410502',
    projectId: 'app-project-6d5d5',
    storageBucket: 'app-project-6d5d5.appspot.com',
    iosClientId: '831849410502-n5esuue3tmed7ovfmefavg4mrbcbfjd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.userApplication',
  );
}
